---
# tasks file for ansible-role-filesystem-security

#- name: "Include OS-specific variables"
#  ansible.builtin.include_vars:
#    file: "{{ ansible_os_family }}.yaml"

#- name: "Gather the package facts"
#  ansible.builtin.package_facts:
#    manager: auto
#  when: ansible_facts.packages is not defined

- name: "Ensure filesystem kernel modules are disabled"
  ansible.builtin.lineinfile:
    path: "/etc/modprobe.d/{{ item.kernel_module }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - kernel_module: "cramfs"
      regexp: ^[\s]*cramfs.*\b.*$
      line: "install cramfs /bin/false"
    - kernel_module: "freevxfs"
      regexp: ^[\s]*freevxfs.*\b.*$
      line: "install freevxfs /bin/false"
    - kernel_module: "hfs"
      regexp: ^[\s]*hfs.*\b.*$
      line: "install hfs /bin/false"
    - kernel_module: "hfsplus"
      regexp: ^[\s]*hfsplus.*\b.*$
      line: "install hfsplus /bin/false"
    - kernel_module: "jffs2"
      regexp: ^[\s]*jffs2.*\b.*$
      line: "install jffs2 /bin/false"
    - kernel_module: "squashfs"
      regexp: ^[\s]*squashfs.*\b.*$
      line: |
        blacklist squashfs
        install squashfs /bin/false
    - kernel_module: "udf"
      regexp: ^[\s]*udf.*\b.*$
      line: "install udf /bin/false"
    - kernel_module: "usb-storage"
      regexp: ^[\s]*usb-storage.*\b.*$
      line: "install usb-storage /bin/false"

- name: "Check for 'nodev' mount option for /boot/efi mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/boot/efi"
    option: "nodev"
  when: ansible_facts['distribution'] == 'Debian'

- name: "Check for 'nodev' mount option for /dev/shm mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/dev/shm"
    option: "nodev"

- name: "Check for 'noexec' mount option for /dev/shm mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/dev/shm"
    option: "noexec"

- name: "Check for 'nosuid' mount option for /dev/shm mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/dev/shm"
    option: "nosuid"

- name: "Check for 'nodev' mount option for /home mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/home"
    option: "nodev"

- name: "Check for 'nosuid' mount option for /home mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/home"
    option: "nosuid"

- name: "Check for 'nodev' mount option for /tmp mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/tmp"
    option: "nodev"

- name: "Check for 'noexec' mount option for /tmp mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/tmp"
    option: "noexec"
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Check for 'nosuid' mount option for /tmp mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/tmp"
    option: "nosuid"

- name: "Check for 'nodev' mount option for /var mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/var"
    option: "nodev"

- name: "Check for 'noexec' mount option for /var mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/var"
    option: "noexec"
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Check for 'nosuid' mount option for /var mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/var"
    option: "nosuid"

- name: "Check for 'nodev' mount option for /var/log mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/var/log"
    option: "nodev"

- name: "Check for 'nodev' mount option for /var/log/audit mount"
  ansible.builtin.include_tasks:
    file: mount_options.yml
  vars:
    mount: "/var/log/audit"
    option: "nodev"

- name: "Update MultiPath Daemon config to blacklist any VMWare Virtual Disks"
  ansible.builtin.blockinfile:
    path: "/etc/multipath.conf"
    backup: yes
    block: |
      blacklist {
        device {
            vendor "VMware"
            product "Virtual disk"
        }
      }
  register: multipath
  when: ansible_facts['distribution'] == 'Debian'

- name: "Restart MultiPath Daemon Service"
  ansible.builtin.service:
    name: multipathd
    state: restarted
  when: multipath.changed