- name: "Collect source device information about {{ mount }} mount"
  ansible.builtin.shell:
    cmd: findmnt -s -o SOURCE '{{ mount }}' | tail -n1
  register: source
  failed_when: source.rc > 1
  changed_when: false

- name: "Collect fstype information about {{ mount }} mount"
  ansible.builtin.shell:
    cmd: findmnt -o FSTYPE '{{ mount }}' | tail -n1
  register: fstype
  failed_when: fstype.rc > 1
  changed_when: false

- name: "Collect mount options information about {{ mount }} mount"
  ansible.builtin.shell:
    cmd: findmnt -s -o OPTIONS '{{ mount }}' | tail -n1
  register: mount_options
  failed_when: mount_options.rc > 1
  changed_when: false

- name: "Collect backup operation information about {{ mount }} mount"
  ansible.builtin.shell:
    cmd: findmnt -s -o FREQ '{{ mount }}' | tail -n1
  register: backup_operation
  failed_when: backup_operation.rc > 1
  changed_when: false

- name: "Collect file system check order information about {{ mount }} mount"
  ansible.builtin.shell:
    cmd: findmnt -s -o PASSNO '{{ mount }}' | tail -n1
  register: check_order
  failed_when: check_order.rc > 1
  changed_when: false

- name: "Set mount_options fact"
  ansible.builtin.set_fact:
    source: "{{ source.stdout }}"
    fstype: "{{ fstype.stdout }}"
    mount_options: "{{ mount_options.stdout }}"
    backup_operation: "{{ backup_operation.stdout | trim }}"
    check_order: "{{ check_order.stdout | trim }}"

- name: "Remove 'defaults' mount options from mount_options var"
  ansible.builtin.set_fact:
    mount_options: "{{ mount_options | replace('defaults','') }}"
  when: "'defaults' in mount_options"

- name: "Remove beginning comma from mount_options var"
  ansible.builtin.set_fact:
    mount_options: "{{ mount_options | replace(',','',1) }}"
  when: mount_options.startswith(',')

- name: "Add specified mount option {{ option }} to {{ mount }}, when mount_options is blank"
  ansible.posix.mount:
    path: "{{ mount }}"
    src: "{{ source }}"
    fstype: "{{ fstype }}"
    opts: "{{ option }}"
    dump: "{{ backup_operation }}"
    passno: "{{ check_order }}"
    state: present
  when:
    - "option not in mount_options"
    - mount_options == ""

- name: "Add specified mount option {{ option }} to {{ mount }}, when mount_options is not blank"
  ansible.posix.mount:
    path: "{{ mount }}"
    src: "{{ source }}"
    fstype: "{{ fstype }}"
    opts: "{{ mount_options }},{{ option }}"
    dump: "{{ backup_operation }}"
    passno: "{{ check_order }}"
    state: present
  when:
    - "option not in mount_options"
    - mount_options != ""