- name: "Collect mount information about {{ mount }} mount"
  ansible.builtin.shell:
    cmd: findmnt '{{ mount }}' | tail -n1 | awk '{ print $4 }'
  register: mount_options
  failed_when: mount_options.rc > 1
  changed_when: false

- name: "Add specified mount option {{ option }} to {{ mount }}"
  ansible.posix.mount:
    path: "{{ mount }}"
    src: tempfs
    fstype: tempfs
    opts: "{{ mount_options.stdout }},{{ option }}"
    state: present
  when: "option not in mount_options.stdout"